stages:
  prepare_dataset:
    cmd: py -m datatrio_ml_collab.dataset
    deps:
      - data/raw/kddcup.csv
    outs:
      - data/processed/dataset.csv

  generate_features:
    cmd: py -m datatrio_ml_collab.features
    deps:
      - data/processed/dataset.csv
    outs:
      - data/processed/features.csv
      - data/processed/labels.csv

  train_model:
    cmd: py -m datatrio_ml_collab.modeling.train
    deps:
      - data/processed/features.csv
      - data/processed/labels.csv
      - src/datatrio_ml_collab/modeling/train.py
    params:
      - train

    outs:
      - models/model.pkl

  predict:
    cmd: py -m datatrio_ml_collab.modeling.predict
    deps:
      - data/processed/features.csv
      - models/model.pkl
    outs:
      - data/processed/predictions.csv