[project]
name = "datatrio_ml_collab"
version = "0.0.1"
description = "Git-based collaborative machine learning project using Git, DVC, CI, and reproducible experiments"
authors = [
  { name = "DataTrio" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = ">=3.10"
dependencies = [
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "pytest",
    "python-dotenv",
    "pyyaml",
    "ruff",
    "scikit-learn",
    "seaborn",
    "tqdm",
    "typer",
]

[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting
