[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "datatrio_ml_collab"
version = "0.0.1"
description = "Git-based collaborative machine learning project using Git, DVC, CI, and reproducible experiments"
authors = [
  { name = "DataTrio" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "cryptography>=50.0.2",
    "dvc[gdrive]>=3.67.1",
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "pyopenssl>=26.4.0",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "tqdm",
    "typer",
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["datatrio_ml_collab"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupytext>=1.19.5",
    "nbstripout>=0.9.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
]

