name: Pre-commit Test

on:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit
        
      - name: Create large test file
        run: |
          python -c "open('large-test-file.txt', 'wb').write(b'0' * 1048577)"
          
      - name: Run pre-commit
        run: pre-commit run --all-files
